import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Common/Navbar";
import QueryProvider from "../providers/QueryProvider"
import { AuthProvider } from "@/providers/AuthProvider";
import Footer from "@/Components/Common/Footer";


const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '600', '700'] })

export const metadata = {
  title: "Meal Sets",
  description: "A hostel management system. Generated by nrstc.com",
  icons: {
    icon: "/images/icons/favicon.ico", // path inside /public
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <AuthProvider >
          <QueryProvider>
            <Navbar />
            {children}
            <Footer />
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
